from Player import Player

class Table:
    def __init__(self):
        ...

    def identifyTurnPlayer(self) -> Player:
        ...

    def getStatus(self) -> int:
        ...

    def setTableStatus(self, status: int):
        ...

    def isSet(self, cards: list) -> bool:
        ...

    def isSequence(self, cards: list) -> bool:
        ...

    def buyDeck(self):
        ...

    def discardDeck(self):
        ...

    def receive_withdrawal_notification(self):
        ...

    def start_match(self):
        ...

    def reset_game(self):
        ...
    
    def receive_move(self, a_move):
        ...

    def distribute_cards(self):
        ...

    def getGUIImage(self):
        ...

    def resetPlayerQueue(self):
        ...

    def orderPlayerQueue(self):
        ...
    
    def applyPenaltyToOtherPlayers(self, playersQueue: list):
        ...

    def applyPenaltyToPlayer(self, player: Player):
        ...

    def endRound(self):
        ...

    def verifyEndOfMatch(self, playersQueue: list) -> bool:
        ...
    
